### ISSUE TITLE
BookBlock without jQuery

### ISSUE THREAD

**Issue by fidoboy** [codrops/BookBlock#37]
I'm trying to use this library but without using jQuery, i've noticed that there is a bookblock.js https://github.com/codrops/BookBlock/blob/master/js/bookblock.js that doesn't seems to use it but i can't get it working. Can anyone provide a simple example showing how to initialize the page?

**Comment by Kembreg** [comment]
Botelho, I really want to use the plugin but cannot get it to work.  The demo pages have a lot of inline javascript.  Is that needed? I would have thought that being a plugin, all the code is in the plugin.

I wrote this code to insert images after the page has loaded.  What I am doing wrong?  (It's does not work)

$.getScript('//www.mysite.com/modernizr.custom.js'); 
$.getScript('//www.mysite.com/jquerypp.custom.js'); 
$.getScript('//www.mysite.com/jquery.bookblock.js'); 
HTMLtoAppend="<div class='bb-item'>";
HTMLtoAppend+='<a href="example.com">';
HTMLtoAppend+='<img src="example.jpg" width="400" height="300">';
HTMLtoAppend+='</a></div>';
$('#bb-bookblock').append(HTMLtoAppend);
$('#bb-bookblock').bookblock();
$('#bb-next').on('click', function() { $( '#bb-bookblock').bookblock('next') });
$('#bb-prev').on('click', function() { $( '#bb-bookblock').bookblock('prev') });

Thanks for your help!

David
