### ISSUE TITLE
Page Flicker in Chrome for Mac

### ISSUE THREAD

**Issue by cnkevinlee** [codrops/BookBlock#48]
Chrome Version 39.0.2171.71 (64-bit)
Mac OS X 10.10.1

**Comment by kothinti** [comment]
I too face the same issue! The page flickers in chrome and safari on Mac

**Comment by JehandadK** [comment]
Flicker exactly how. This happens with me when using for large images.
![screenshot 2015-06-02 16 00 09](https://cloud.githubusercontent.com/assets/5552134/7934417/9292730a-0940-11e5-8d0e-d71584d1814d.png)

**Comment by JehandadK** [comment]
Solved it changing the opacity to transparent in the background of bb-inner class.

```
.bb-page > div,
.bb-outer,
.bb-content,
.bb-inner {
 background: rgba(255, 255, 255, .1);
}
```

**Comment by cnkevinlee** [comment]
Thank you very much! Once I thought it's a problem of Chrome...

**Comment by JehandadK** [comment]
The fix is only required for chrome, so this is definitely a chrome bug. Also, introducing this fix has created a lag on opera.

**Comment by crnacura** [comment]
Thanks a lot, I have added a fix for this to the CSS.
