### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by IonicaBizau** [codrops/BookBlock#53]
Suppose I need a feature.
I would like to contribute to this project adding it, but I see there are already 3 pull requests that are not merged for a long time.

Also, the license is not ~~friendly~~ open-source. :sob: 
If this is not maintained anymore, can I smoothly fork this project and maintain my own fork? :thought_balloon:

**Comment by crnacura** [comment]
The 3 pull requests are merged now and you are of course free to fork this project. Trying to keep up with more than 120 repos here, so some notifications got lost, I'm sorry about that. 
Can you explain yourself better regarding what you mean with "the license is not ~~friendly~~ open-source"?

**Comment by IonicaBizau** [comment]
@crnacura Oh, thanks! :+1: In the meantime I decided to work on my solution being inspired from this project.

The [license](http://tympanus.net/codrops/licensing/) says: 

> You are not allowed to take our work “as-is” and sell it, redistribute or re-publish it (with the exception of forking our GitHub repos), or sell “pluginized” versions of it.

This makes this repository a non-open-source thing. The open-source licenses grant redistributing and selling modified versions of the software.

**Comment by crnacura** [comment]
The JavaScript files are licensed under MIT.  This gives you the freedom to create your own version and do whatever an open source license grants you to do.

With our license for the whole project/work/demo we try to avoid that 1. our demos get republished 2. the resource gets sold without (significant) modification.

**Comment by IonicaBizau** [comment]
@crnacura Got it! Thanks for clarifying! :cake:
Maybe it would be even better to add that in README and create a `LICENSE` file.

Anyway, glad to hear the js files are licensed under MIT. Happy holidays and happy new year! :smile: :fireworks:
